const express = require("express");
const session = require("express-session");
const path = require("path");
const fs = require("fs");
const multer = require("multer");

const app = express();
const PORT = process.env.PORT || 3000;

const ADMIN_USER = process.env.ADMIN_USER || "admin";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "cambiar-esta-clave";

const ROOT = __dirname;
const UPLOAD_DIR = path.join(ROOT, "public", "uploads");

fs.mkdirSync(UPLOAD_DIR, { recursive: true });

/*
  NONNA PIZZAS
  Base de datos:
  - Local: SQLite
  - Render: PostgreSQL mediante DATABASE_URL
*/

const usePostgres = !!process.env.DATABASE_URL;

let db;
let pgPool = null;
let sqlite = null;

async function initDatabase() {
  if (usePostgres) {
    const { Pool } = require("pg");

    pgPool = new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.NODE_ENV === "production"
        ? { rejectUnauthorized: false }
        : false
    });

    db = {
      query: async (text, params = []) => {
        return pgPool.query(text, params);
      }
    };

    await db.query(`
      CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
      );

      CREATE TABLE IF NOT EXISTS products (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        description TEXT DEFAULT '',
        price INTEGER NOT NULL DEFAULT 0,
        image TEXT DEFAULT '',
        active INTEGER NOT NULL DEFAULT 1,
        featured INTEGER NOT NULL DEFAULT 0,
        sort_order INTEGER NOT NULL DEFAULT 0
      );
    `);

    console.log("Base de datos PostgreSQL conectada.");
  } else {
    const sqliteSync = require("sqlite-sync");

    const dbPath = path.join(ROOT, "nonna.db");
    sqliteSync.connect(dbPath);
    sqlite = sqliteSync;

    sqlite.run(`
      CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
      );

      CREATE TABLE IF NOT EXISTS products (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        description TEXT DEFAULT '',
        price INTEGER NOT NULL DEFAULT 0,
        image TEXT DEFAULT '',
        active INTEGER NOT NULL DEFAULT 1,
        featured INTEGER NOT NULL DEFAULT 0,
        sort_order INTEGER NOT NULL DEFAULT 0
      );
    `);

  db = {
  query: async (sql, params = []) => {
    const result = sqlite.run(sql, params);

    /*
      sqlite-sync puede devolver una consulta SELECT
      con esta estructura:

      [
        {
          columns: ["id", "name", ...],
          values: [
            [1, "Muzzarella", ...],
            [2, "Jamón y Morrón", ...]
          ]
        }
      ]

      Convertimos esa estructura a:

      [
        {
          id: 1,
          name: "Muzzarella",
          ...
        }
      ]
    */

    let data = result;

    // sqlite-sync puede envolver el resultado en un array
    if (
      Array.isArray(data) &&
      data.length === 1 &&
      data[0] &&
      Array.isArray(data[0].columns) &&
      Array.isArray(data[0].values)
    ) {
      data = data[0];
    }

    // Resultado SELECT con columns + values
    if (
      data &&
      Array.isArray(data.columns) &&
      Array.isArray(data.values)
    ) {
      const rows = data.values.map(values => {
        const row = {};

        data.columns.forEach((column, index) => {
          row[column] = values[index];
        });

        return row;
      });

      return {
        rows,
        rowCount: rows.length
      };
    }

    // Resultado que ya viene como array de objetos
    if (Array.isArray(data)) {
      return {
        rows: data,
        rowCount: data.length
      };
    }

    // Consultas que no devuelven filas
    return {
      rows: [],
      rowCount: 0
    };
  }
};

    console.log("Base de datos SQLite local conectada.");
  }

  await seedDatabase();
}

const defaults = {
  business_name: "NONNA PIZZAS",
  open: "true",
  schedule: "Lunes a Domingo · 19:00 a 00:00",
  phone: "5493755208648",
  instagram: "https://www.instagram.com/",
  latitude: "-27.292740",
  longitude: "-54.206261",
  delivery_price: "3000",
  cooked_extra: "3000",
  filled_edge_extra: "3000"
};

const initialProducts = [
  [
    "Muzzarella",
    "pizzas",
    "Salsa, muzzarella, aceitunas y orégano.",
    8000,
    "assets/muzzarella.jpeg",
    1,
    1,
    1
  ],
  [
    "Jamón y Morrón",
    "pizzas",
    "Muzzarella, jamón y morrón.",
    10000,
    "",
    1,
    0,
    2
  ],
  [
    "Choclo",
    "pizzas",
    "Muzzarella y choclo.",
    10000,
    "",
    1,
    0,
    3
  ],
  [
    "Salame",
    "pizzas",
    "Muzzarella y salame.",
    10000,
    "",
    1,
    0,
    4
  ],
  [
    "Calabresa",
    "pizzas",
    "Muzzarella, calabresa, aceitunas y orégano.",
    10000,
    "assets/calabresa.jpeg",
    1,
    1,
    5
  ],
  [
    "Choclo y Salame",
    "pizzas",
    "Muzzarella, choclo y salame.",
    10000,
    "",
    1,
    0,
    6
  ],
  [
    "Jamón y Choclo",
    "pizzas",
    "Muzzarella, jamón y choclo.",
    10000,
    "",
    1,
    0,
    7
  ],
  [
    "Strogonoff de Pollo",
    "especiales",
    "Strogonoff de pollo con borde relleno incluido.",
    18000,
    "",
    1,
    0,
    8
  ],
  [
    "Calabresa con Borde Relleno",
    "especiales",
    "Calabresa con borde relleno incluido.",
    15000,
    "",
    1,
    0,
    9
  ],
  [
    "Choclo y Salame con Borde Relleno",
    "especiales",
    "Choclo y salame con borde relleno incluido.",
    15000,
    "",
    1,
    0,
    10
  ],
  [
    "Strogonoff de Carne",
    "especiales",
    "Strogonoff de carne con borde relleno incluido.",
    18000,
    "",
    1,
    0,
    11
  ]
];

async function seedDatabase() {
  for (const [key, value] of Object.entries(defaults)) {
    if (usePostgres) {
      await db.query(
        `INSERT INTO settings (key, value)
         VALUES ($1, $2)
         ON CONFLICT (key) DO NOTHING`,
        [key, value]
      );
    } else {
      await db.query(
        `INSERT OR IGNORE INTO settings (key, value)
         VALUES (?, ?)`,
        [key, value]
      );
    }
  }

  const countResult = await db.query(
    `SELECT COUNT(*) AS count FROM products`
  );

  const count = Number(countResult.rows[0]?.count || 0);

  if (count === 0) {
    for (const product of initialProducts) {
      if (usePostgres) {
        await db.query(
          `INSERT INTO products
           (name, category, description, price, image, active, featured, sort_order)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
          product
        );
      } else {
        await db.query(
          `INSERT INTO products
           (name, category, description, price, image, active, featured, sort_order)
           VALUES (?,?,?,?,?,?,?,?)`,
          product
        );
      }
    }
  }
}

app.use(express.json({ limit: "2mb" }));
app.use(express.urlencoded({ extended: true }));

app.use(
  session({
    secret:
      process.env.SESSION_SECRET ||
      "nonna-session-secret-change-me",
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      maxAge: 8 * 60 * 60 * 1000
    }
  })
);

app.use(express.static(path.join(ROOT, "public")));

app.set("trust proxy", 1);

app.use(
  session({
    secret:
      process.env.SESSION_SECRET ||
      "nonna-session-secret-change-me",
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      maxAge: 8 * 60 * 60 * 1000
    }
  })
);
async function setting(key) {
  const result = usePostgres
    ? await db.query(
        `SELECT value FROM settings WHERE key=$1`,
        [key]
      )
    : await db.query(
        `SELECT value FROM settings WHERE key=?`,
        [key]
      );

  return result.rows[0]?.value ?? "";
}

async function allSettings() {
  const result = await db.query(`SELECT key,value FROM settings`);

  return Object.fromEntries(
    result.rows.map(row => [row.key, row.value])
  );
}

function adminOnly(req, res, next) {
  if (req.session.admin) return next();

  return res.status(401).json({
    error: "No autorizado"
  });
}

/* =========================
   CONFIGURACIÓN PÚBLICA
========================= */

app.get("/api/public-config", async (req, res) => {
  try {
    res.set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
    res.set("Pragma", "no-cache");
    res.set("Expires", "0");

    const s = {
      businessName: await setting("business_name"),
      open: (await setting("open")) === "true",
      schedule: await setting("schedule"),
      phone: await setting("phone"),
      instagram: await setting("instagram"),
      latitude: Number(await setting("latitude")),
      longitude: Number(await setting("longitude")),
      deliveryPrice: Number(await setting("delivery_price")),
      cookedExtra: Number(await setting("cooked_extra")),
      filledEdgeExtra: Number(await setting("filled_edge_extra"))
    };

    const productsResult = await db.query(`
      SELECT
        id,
        name,
        category,
        description,
        price,
        image,
        active,
        featured,
        sort_order
      FROM products
      WHERE active=1
      ORDER BY category, sort_order, id
    `);

    res.json({
      settings: s,
      products: productsResult.rows
    });
  } catch (error) {
    console.error("Error cargando configuración pública:", error);

    res.status(500).json({
      error: "No se pudo cargar la configuración"
    });
  }
});

/* =========================
   LOGIN ADMIN
========================= */

app.post("/api/admin/login", (req, res) => {
  const { username, password } = req.body;

  if (
    username === ADMIN_USER &&
    password === ADMIN_PASSWORD
  ) {
    req.session.admin = true;

    return res.json({
      ok: true
    });
  }

  res.status(401).json({
    error: "Usuario o contraseña incorrectos"
  });
});

app.post("/api/admin/logout", (req, res) => {
  req.session.destroy(() => {
    res.json({
      ok: true
    });
  });
});

app.get("/api/admin/me", (req, res) => {
  res.json({
    authenticated: !!req.session.admin
  });
});

/* =========================
   CONFIGURACIÓN ADMIN
========================= */

app.put("/api/admin/settings", adminOnly, async (req, res) => {
  const allowed = [
    "business_name",
    "open",
    "schedule",
    "phone",
    "instagram",
    "latitude",
    "longitude",
    "delivery_price",
    "cooked_extra",
    "filled_edge_extra"
  ];

  try {
    for (const key of allowed) {
      if (req.body[key] === undefined) continue;

      const value = String(req.body[key]);

      if (usePostgres) {
        await db.query(
          `INSERT INTO settings(key,value)
           VALUES($1,$2)
           ON CONFLICT(key)
           DO UPDATE SET value=EXCLUDED.value`,
          [key, value]
        );
      } else {
        const update = await db.query(
          `UPDATE settings SET value=? WHERE key=?`,
          [value, key]
        );

        if (update.rowCount === 0) {
          await db.query(
            `INSERT INTO settings(key,value)
             VALUES(?,?)`,
            [key, value]
          );
        }
      }
    }

    res.set("Cache-Control", "no-store");

    res.json({
      ok: true,
      settings: await allSettings()
    });
  } catch (error) {
    console.error("Error guardando configuración:", error);

    res.status(500).json({
      error: "No se pudo guardar la configuración"
    });
  }
});

/* =========================
   PRODUCTOS
========================= */

app.post("/api/admin/products", adminOnly, async (req, res) => {
  try {
    const {
      name,
      category,
      description = "",
      price = 0,
      image = "",
      active = 1,
      featured = 0
    } = req.body;

    if (!name || !category) {
      return res.status(400).json({
        error: "Nombre y categoría son obligatorios"
      });
    }

    const maxResult = usePostgres
      ? await db.query(
          `SELECT COALESCE(MAX(sort_order),0) AS max
           FROM products
           WHERE category=$1`,
          [category]
        )
      : await db.query(
          `SELECT COALESCE(MAX(sort_order),0) AS max
           FROM products
           WHERE category=?`,
          [category]
        );

    const maxOrder = Number(
      maxResult.rows[0]?.max || 0
    );

    if (usePostgres) {
      const result = await db.query(
        `INSERT INTO products
         (name,category,description,price,image,active,featured,sort_order)
         VALUES($1,$2,$3,$4,$5,$6,$7,$8)
         RETURNING id`,
        [
          name,
          category,
          description,
          Number(price) || 0,
          image,
          active ? 1 : 0,
          featured ? 1 : 0,
          maxOrder + 1
        ]
      );

      return res.json({
        ok: true,
        id: result.rows[0].id
      });
    }

    const result = await db.query(
      `INSERT INTO products
       (name,category,description,price,image,active,featured,sort_order)
       VALUES(?,?,?,?,?,?,?,?)`,
      [
        name,
        category,
        description,
        Number(price) || 0,
        image,
        active ? 1 : 0,
        featured ? 1 : 0,
        maxOrder + 1
      ]
    );

    res.json({
      ok: true,
      id: null
    });
  } catch (error) {
    console.error("Error creando producto:", error);

    res.status(500).json({
      error: "No se pudo crear el producto"
    });
  }
});

app.put("/api/admin/products/:id", adminOnly, async (req, res) => {
  try {
    const {
      name,
      category,
      description = "",
      price = 0,
      image = "",
      active = 1,
      featured = 0
    } = req.body;

    const params = [
      name,
      category,
      description,
      Number(price) || 0,
      image,
      active ? 1 : 0,
      featured ? 1 : 0,
      req.params.id
    ];

    if (usePostgres) {
      await db.query(
        `UPDATE products
         SET name=$1,
             category=$2,
             description=$3,
             price=$4,
             image=$5,
             active=$6,
             featured=$7
         WHERE id=$8`,
        params
      );
    } else {
      await db.query(
        `UPDATE products
         SET name=?,
             category=?,
             description=?,
             price=?,
             image=?,
             active=?,
             featured=?
         WHERE id=?`,
        params
      );
    }

    res.json({
      ok: true
    });
  } catch (error) {
    console.error("Error actualizando producto:", error);

    res.status(500).json({
      error: "No se pudo actualizar el producto"
    });
  }
});

app.delete("/api/admin/products/:id", adminOnly, async (req, res) => {
  try {
    const imageResult = usePostgres
      ? await db.query(
          `SELECT image FROM products WHERE id=$1`,
          [req.params.id]
        )
      : await db.query(
          `SELECT image FROM products WHERE id=?`,
          [req.params.id]
        );

    const product = imageResult.rows[0];

    if (product?.image?.startsWith("/uploads/")) {
      const file = path.join(
        UPLOAD_DIR,
        path.basename(product.image)
      );

      if (fs.existsSync(file)) {
        fs.unlinkSync(file);
      }
    }

    if (usePostgres) {
      await db.query(
        `DELETE FROM products WHERE id=$1`,
        [req.params.id]
      );
    } else {
      await db.query(
        `DELETE FROM products WHERE id=?`,
        [req.params.id]
      );
    }

    res.json({
      ok: true
    });
  } catch (error) {
    console.error("Error eliminando producto:", error);

    res.status(500).json({
      error: "No se pudo eliminar el producto"
    });
  }
});

/* =========================
   SUBIDA DE IMÁGENES
========================= */

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, UPLOAD_DIR);
  },

  filename: (req, file, cb) => {
    const ext = path
      .extname(file.originalname)
      .toLowerCase();

    const safe =
      Date.now() +
      "-" +
      Math.random()
        .toString(36)
        .slice(2, 8) +
      ext;

    cb(null, safe);
  }
});

const upload = multer({
  storage,

  limits: {
    fileSize: 4 * 1024 * 1024
  },

  fileFilter: (req, file, cb) => {
    const ok = [
      "image/jpeg",
      "image/png",
      "image/webp",
      "image/jpg"
    ].includes(file.mimetype);

    cb(
      ok
        ? null
        : new Error("Solo JPG, PNG o WEBP"),
      ok
    );
  }
});

app.post(
  "/api/admin/upload",
  adminOnly,
  upload.single("image"),
  (req, res) => {
    if (!req.file) {
      return res.status(400).json({
        error: "No se recibió imagen"
      });
    }

    res.json({
      ok: true,
      url: "/uploads/" + req.file.filename
    });
  }
);

/* =========================
   MANEJO DE ERRORES
========================= */

app.use((err, req, res, next) => {
  if (err) {
    console.error(err);

    return res.status(400).json({
      error: err.message || "Error"
    });
  }

  next();
});

/* =========================
   RUTAS WEB
========================= */

app.get("/admin", (req, res) => {
  res.sendFile(
    path.join(ROOT, "public", "admin.html")
  );
});

app.get("*", (req, res) => {
  if (req.path.startsWith("/api/")) {
    return res.status(404).end();
  }

  res.sendFile(
    path.join(ROOT, "public", "index.html")
  );
});

/* =========================
   ARRANQUE
========================= */

async function startServer() {
  try {
    await initDatabase();

    app.listen(PORT, () => {
      console.log(
        `NONNA PIZZAS funcionando en http://localhost:${PORT}`
      );

      console.log(
        `Base utilizada: ${usePostgres ? "PostgreSQL" : "SQLite"}`
      );
    });
  } catch (error) {
    console.error(
      "No se pudo iniciar NONNA PIZZAS:",
      error
    );

    process.exit(1);
  }
}

startServer();

